server{
  #port on which it listens
  listen 80; 

  root /usr/share/nginx/html; #root directory of the server

  index index.html; #default file to server

  location / {
    try_files $uri $uri/ /index.html; #try to serve the file, if not found return the index.html file
  }


}
